### ISSUE TITLE
When you open up app - Planet Patrol is really stretched and covering Ts & Cs message

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#104]
See image
![IMG-5636](https://user-images.githubusercontent.com/62663054/83973607-a3f2e780-a8df-11ea-87ef-c90ee2975c84.PNG)

**Comment by munroTom** [comment]
@lizheard1 has this been fixed now? I've got an android need to wait for the beta to be published to test

**Comment by lizheard1** [comment]
@munroTom yes it is fixed on apple
