### ISSUE TITLE
In agreeing to Ts & Cs, change to 'Welcome to Planet Patrol'

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#105]
See image for reference
![IMG-5637](https://user-images.githubusercontent.com/62663054/83973642-c7b62d80-a8df-11ea-89df-41d572b6cf0a.PNG)

**Comment by munroTom** [comment]
@lizheard1 just going through and updating now, have you set up new twitter handles for the rebrand?

**Comment by lizheard1** [comment]
@munroTom the change is ONLY to the app name - the brand is still called Plastic Patrol and so all our social handles are the same. So the organisation and brand is called Plastic Patrol and our app is called Planet Patrol (most organisations that have an app as one of their 'services' don't have the same name for both) - does this make sense? Therefore we only need to change wording where we say things like 'welcome to Plastic Patrol' when we are referring to the app
