### ISSUE TITLE
Set up api to add / update / find products

### ISSUE THREAD

**Issue by munroTom** [PlasticPatrol/PlasticPatrolWeb#11]
### Database
Is there a database of products available for us to use?

If not then what information do we need?
Brand, product name, photo, plastic free, what else?

### Permissions
Are all users allowed to add / update products or a select group e.g. moderators only?

**Comment by munroTom** [comment]
Follow up from email discussion:
- Who can add products: similar system to photos, anyone can add information but only moderators can approve
- Schema: brand, manufacturer, product, plasticPatrolCertified, dateAdded, countryOfOrigin, (extra fields for moderation: dateTimeApproved, approved)

- https://www.barcodelookup.com/ (found by @neilfulwiler ) can provide us with brand, manufacturer and product

Proposed solution:
As barcode lookup doesn't provide us with everything we could have a flow like this:
We maintain a database with all the information that we want
1) user scans barcode in the app
2) we do a lookup for that barcode, if it exists in our database send the information we have back to the user
3) If it doesn't we send the request on to barcodelookup, get whatever meta information we can from there
4) when this response comes back we save it in our database and send the result back to the user
5) on the front end users get returned this information and they'll get a prompt `want to add some more information?` where they can add anything we can't get from barcode lookup e.g. country of origin
6) this will then go to a pending state in the database, once it's been approved by an admin all the information can be displayed
If a user does a lookup of the same product before it's approved we can send back the information we get from barcode lookup, so that we don't make additional requests to their service?

Costs of barcode lookup are $99 a month for up to 5000 lookups, $249 for 25000 (further limits can be found [here](https://www.barcodelookup.com/api))

Further questions:
- how does a product get certified, is that decided on a product by product basis? Or will that just be a company reaches out to plastic patrol and proves they're using sustainable resources within their production chain? And then anything that we find belongs to them is `certified`?

**Comment by neilfulwiler** [comment]
What can’t we get from barcode lookup?

**Comment by munroTom** [comment]
> Edit gah sorry I see the schema. Ok I think the three things we can get from barcode lookup get us >90% of the way there, so let’s just punt on the rest of it for now? We can double check with Lizzie but I think that’s the way to go

By that do you mean just use barcode lookup only rather than storing some things ourselves? Just wanting to check I've got the right idea

**Comment by neilfulwiler** [comment]
well we can store the data alongside the picture, but yeah not store our
own canonical mapping from barcode to info. At least as a v1

**Comment by neilfulwiler** [comment]
I think we can close this for now if we agree on not rolling out own storage of types for the time being?

**Comment by munroTom** [comment]
Yeah sounds good to me!
