### ISSUE TITLE
Remove Kwame Asubonteng from leaderboard

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#111]
His 15K pieces is from one image, so obviously dodgy. Please could he be made invisible / not included in the leaderboard?
![image](https://user-images.githubusercontent.com/62663054/84135084-6d34e280-aa41-11ea-80ad-1238cda772df.png)

**Comment by lizheard1** [comment]
@munroTom yes we understand that it may be a realistic number. The reasoning is that there is no point having bags full when we can’t identify the brands - that’s why we need to make the point that we are asking people to tag brands so they know its not just about a collection of litter. The 15K is just a number with no type / brand etc attributed. If that guy wasn’t at the top of the leaderboard it wouldn’t be so bad but it kind of defeats the point of the app if people can just take a photo of bags and bins full of litter and estimate 1000s of pieces in it. If that makes sense? Obviously the app has evolved over time - at the beginning there wasn't categorisation, so there will be images without this. What we want to avoid is people taking photos of bags of rubbish where we can't see the items. So if you could remove the guy from the leaderboard - he's only uploaded one photo so isn't even using the app anymore x

**Comment by neilfulwiler** [comment]
ok @munroTom @lizheard1 my proposal is to add functionality to the stats.json endpoint that splits out "large collections" into their own thing (any photo that has >1000 pieces or whatever). these will be counted separately and then on the frontend we can add some toggle or setting for displaying the leaderboard with these stats (by default we won't include large collections in people's tallies on the leaderboard)
