### ISSUE TITLE
On some new photos uploaded, the date is wrong (says moderated in 1970)

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#129]
E.g. this image (this is a screenshot of what I see in the photo approval section before approved, so I think 'moderated' refers to the date the person uploaded it)

![IMG-6056](https://user-images.githubusercontent.com/62663054/85220204-8e7ec280-b3a1-11ea-8919-05e650a7ade1.PNG)

**Comment by neilfulwiler** [comment]
photos that havent been moderated have moderated=null. Thats being converted to jan 1, 1970. I can fix this in the moderator view
