### ISSUE TITLE
Get listed in the Google Play Store as a TWA

### ISSUE THREAD

**Issue by munroTom** [PlasticPatrol/PlasticPatrolWeb#13]
Google now have a feature where you can get listed as a TWA in the app store rather than a hybrid app.

The company I work for currently has been investigating this and it seems like it was relatively easy to do (even more so if we're already listed I imagine!).  I think it came with a one time cost of about $25

Advantages:
- we're no longer tied to google on our release cycle, once a new versions out there when users go back to the app they should be able to fetch it (provided the service worker doesn't keep it cached)

Disadvantages:
- from trialling our web app in beta it doesn't have quite the same feel as a regular app. Sometimes the topbar from google does display when scrolling
- it is also possible to do this with apple as well, however it is more expensive and you have to pay on an annual subscription
- if we don't continue to list in the apple app store we'll lose the easy flow for them to download

As @sebastianovide  a PWA only (no listing in any stores) it is still possible for users to have the app with a similar feel. On android phones if they visit `app.plasticpatrol.co.uk` they'll get a prompt asking if they want to add it to homescreen and from there they will have an app like experience. Users on iOS devices can also add to homescreen but they have go into their settings and choose to add it rather than being asked if they want to do it

https://developers.google.com/web/android/trusted-web-activity

**Comment by neilfulwiler** [comment]
Unfortunately I think that having an actual app, even if actual is basically semantic and not really meaningful, is important for people. It would be important for me anyway. I think it’s just too much friction to ask people to install/use a PWA.

As for the benefits, I just don’t know enough about this space t understand this. Not being tied to google would mean that instead of someone having to explicitly (or implicitly via auto update) upgrade, they would just pull the new version whenever they go to the app?

**Comment by sebastianovide** [comment]
I would say the the biggest benefits for PP is the overhead **cost** associated to it. 
All the rest is less relevant. For example, the time to release and update a new version (some people update the app once a week or even once a month and Apple can take days to approve and once in a while they reject !), could be implemented with code pushing....

**Comment by munroTom** [comment]
> Not being tied to google would mean that instead of someone having to explicitly (or implicitly via auto update) upgrade, they would just pull the new version whenever they go to the app? 

Yeah, so with a TWA new versions of the app would be downloaded in the background by the service worker and then when they close the app the new one will install itself
This post explains the service worker lifecycle in a little more detail https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle

**Comment by lizheard1** [comment]
@munroTom what is this?

**Comment by munroTom** [comment]
@lizheard1 it was a suggestion for updating our play store listing so that we don't have to go through the same release process with beta etc. however if we're still needing to build with cordova for the app store it's probably not worth it as it will come with additional effort to get it set up in the first place and ensure everything still works as we expect
