### ISSUE TITLE
Can't 'see on google map' when approving a photo

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#132]
There is a bug for moderators where when you click on  'see google map' (see screenshot for reference) nothing happens.

When I go to app.plasticpatrol on my laptop this does work. So it's either a bug for the mobile app or iphones
![IMG-6151](https://user-images.githubusercontent.com/62663054/85445101-edebf680-b58a-11ea-9de4-5d7685a13594.PNG)

**Comment by munroTom** [comment]
@lizheard1 does this work for you on https://plastic-patrol-dev-722eb.web.app/#/ ? I recently made some changes to this component which aren't on the latest version in the app store, I've checked on my phone on the web-app version and it seems ok

**Comment by lizheard1** [comment]
@munroTom yes this works on web app - so I guess with the next update this will work too? I'll work from the web app for approving photos for now

**Comment by lizheard1** [comment]
@munroTom this works for me now, so okay to close the issue

**Comment by munroTom** [comment]
@lizheard1 ah I see, when you said web app I assume you meant app.plasticpatrol.co.uk not the dev one but fair enough!
