### ISSUE TITLE
Upload times too long - need to speed up

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#134]
Some users have said that their images are not uploading. They take the time to record items, then hit submit, then the 'please be patient' message comes up and it gets stuck at a % (e.g. one user was at 99% for 8 minutes). How can we stop this from happening? This is in homes where they have wifi that works for everything else.

**Comment by munroTom** [comment]
Context on moving the bucket location: https://cloud.google.com/storage/docs/moving-buckets

I think we'll also need to update some of the cloud functions too so that we can generate the thumbnails etc.

**Comment by lizheard1** [comment]
@munroTom what are the next steps here - do you need me to look at that link, or is this something for you and Neil to discuss?

**Comment by munroTom** [comment]
@lizheard1 yeah it's just something that needs working on - I was just putting the link there to save whoever picks this up from searching

**Comment by sebastianovide** [comment]
I strongly doubt that changing bucket will make any difference.  99% for 8 minutes smells as a bug.... need to find a way to reproduce it in house. Perhaps upload photos and break the connection in between...

**Comment by sebastianovide** [comment]
just to confirm that I can easily reproduce it using Chrome disabling the network while uploading. 
steps to reproduce
===

- open development tool
- in the network tab set 3G slow
- upload a photo
- when it is over 90% set the network as offline
- wait few minutes
- turn the network online

expected
===
- either give an error (and as a bonus rollback any data already uploaded)
- or continue the upload

instead
===
- it is blocked to 9x% for ever

**Comment by sebastianovide** [comment]
after #207 it "wait" until when the networks is back. The cancel button is present so it can also be cancelled.
