### ISSUE TITLE
Investigate users with very large stats

### ISSUE THREAD

**Issue by munroTom** [PlasticPatrol/PlasticPatrolWeb#14]
Email from Liz:

I've just noticed that the totaliser for the number of pieces recorded in the app has gone over one million, which is a rapid jump. I had a look at the leaderboard and it looks like a user called Chandu artl has uploaded 863944 pieces which I struggle to believe and think is an error - see below:

![image](https://user-images.githubusercontent.com/29929268/77683286-10707280-6f90-11ea-8463-cc0771be62dc.png)

Please could you have a look at the user and the image / data they uploaded - I think they were just being an idiot and inputting the wrong number. If so please could the image and data be removed?

**Comment by munroTom** [comment]
@sebastianovide or @neilfulwiler would it be possible to upgrade my permissions in firebase to allow me to remove the photo?

The photo is [UNaazflfBwCdceT3bsYR](https://storage.googleapis.com/plastic-patrol-fd3b3.appspot.com/photos/UNaazflfBwCdceT3bsYR/original.jpg) I've looked a little further down and there are some that could do with clearing up as well (I'm currently 12th on the leaderboard due to my test photos... )

**Comment by munroTom** [comment]
Don't know if this something that is worth making into a script so that the entry in the database and corresponding photo is deleted (or if something like that already exists?)

**Comment by neilfulwiler** [comment]
Yup sorry I missed this, I’ll give you access

**Comment by neilfulwiler** [comment]
@munroTom I believe Lizzie has given you access, do you have the right permissions now?

**Comment by lizheard1** [comment]
@munroTom did you get the permissions for this? The figure for total pieces is still saying over 1 million on the app (and website as it is pulled from the app) which is incorrect and misleading. Please could this get altered as a priority? Thanks x

**Comment by munroTom** [comment]
@neilfulwiler @lizheard1 it's still saying that I have view only permissions so I'm not able to make any changes - the email that I'm using for firebase is `munfro@gmail.com`

I'll take a look into how the total number of pieces is calculated (check whether it gets this directly from the database or if it only updates when a picture is approved) so I know what to do when I've updated the individual users stats

**Comment by munroTom** [comment]
Cool - looks like it increments the previous count so I'll just edit both when I make the changes

**Comment by munroTom** [comment]
To safeguard against this sort of thing in the future would it be worth having some validation when admins approve photos?
e.g. just a simple "warning: you're about to approve a photo with > X pieces in it, are you sure the count is correct?"

**Comment by lizheard1** [comment]
@munroTom thank you! Yes I think a warning feature like that would be good - I would have the warning for 50 pieces and up? Also, how do I tag Lizzie in a comment here? She has a Github account by when I type in @lizzie... etc she doesn't come up?

**Comment by munroTom** [comment]
@lizheard1 cool I've made an issue for it: https://github.com/PlasticPatrol/PlasticPatrolWeb/issues/26

I'm not sure exactly why the `@` doesn't give Lizzie as a suggestion (although you have tagged someone else)
I guess it might be because she's not part of this thread or the organisation that's been set up yet and has no commits in the repository as all that seems to be the common denominator in all of the suggestions I've got
If you know what her github name is if you @`handle for lizzie goes here` it will tag her (like the Lizzie in your comment)

**Comment by munroTom** [comment]
Have gone through and updated that users stats (and my own)
Looks like there's a cache somewhere storing that value and I'm not sure on how to reset it so will take a little bit of time to update, if it doesn't change in the next couple of days I'll reach out to Seb to find out how to do this manually.
