### ISSUE TITLE
Add 'check your junk folder' to the confirmation text when someone signs up for an account

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#148]
The verfication email sometimes goes through to people's junk. Please could we add 'Check your junk folder just in case!' to the end of the 'email sent' text? Thanks

**Comment by munroTom** [comment]
Current screen for checking email:
<img width="628" alt="Screenshot 2020-07-25 at 08 57 35" src="https://user-images.githubusercontent.com/29929268/88452234-f4ed7980-ce54-11ea-8139-8dd72577551b.png">

Don't know if `spam` -> `junk` will necessarily be any clearer?
