### ISSUE TITLE
Update tags and description in play store

### ISSUE THREAD

**Issue by munroTom** [PlasticPatrol/PlasticPatrolWeb#149]
@lizheard1 here's a link to the tags where you can choose what applies best:
https://play.google.com/apps/publish/?account=5299823328690523271#AnnotationPagePlace:p=uk.co.plasticpatrol

If you follow this link you can update the store listing yourself including the app description + screenshots:
https://play.google.com/apps/publish/?account=5299823328690523271#MarketListingPlace:p=uk.co.plasticpatrol

If other geographies seem interesting we can translate the app description too

**Comment by lizheard1** [comment]
@munroTom when I click on the links it says I don't have permission to view them - please could you sort the permissions, or copy and paste what you see ? Thanks!

**Comment by lizheard1** [comment]
Lizzie to sort permission

**Comment by lizheard1** [comment]
Linked old issue https://github.com/PlasticPatrol/PlasticPatrolWeb/issues/78
