### ISSUE TITLE
Freezing during uploads

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#153]
I've had this feedback from a user - thoughts on reasons for this, whether there are any quick fixes and how we can approach this?

![image](https://user-images.githubusercontent.com/62663054/87908027-aa878980-ca5d-11ea-9661-b59955b74d45.png)

**Comment by lizheard1** [comment]
To investigate why uploads are freezing and how long upload times take - track this and then we can see how big the problem is and how to fix it

**Comment by lizheard1** [comment]
Also this feedback from a user: 'On several occasions, I have entered all of the data and then clicked ‘submit’ and it just sits there on 0% and says ‘be patient’. I have to come out of the app and start again because even patience doesn’t work.'

**Comment by lizheard1** [comment]
https://github.com/PlasticPatrol/PlasticPatrolWeb/issues/161 - a user said they also said they were unable to submit feedback and saw the loading sign - likely linked to user network problems and may be linked to this issue

**Comment by lizheard1** [comment]
More feedback from a user - let's get this fixed ASAP!
![IMG-7219](https://user-images.githubusercontent.com/62663054/90769916-eb86ee00-e2e8-11ea-85a1-40c4a3139dd2.PNG)

**Comment by lizheard1** [comment]
@neilfulwiler any luck in the past 2 weeks with this? It's v hit and miss with upload speeds x

**Comment by sebastianovide** [comment]
need to test again after #207 goes live
