### ISSUE TITLE
How can someone manually add a geotag - e.g. if collect litter and take pic at home, rather than in situ

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#154]
See user feedback below (a few people have flagged this). Is there a way to do this? How should I respond @neilfulwiler @munroTom 

![image](https://user-images.githubusercontent.com/62663054/87909235-c855ee00-ca5f-11ea-8eb3-edad47bb9f65.png)
![image](https://user-images.githubusercontent.com/62663054/87909572-66e24f00-ca60-11ea-9568-0c79ab22daab.png)

**Comment by munroTom** [comment]
It seems like mapbox does offer this sort of feature so it potentially wouldn't be super difficult to do https://docs.mapbox.com/mapbox-gl-js/example/mouse-position/

I think the main issues are in trying to make it a user friendly experience
- how should this tie in with the categorisation journey? Do they get shown a dialog and then taken to the map to add the location, should we maybe do it in a separate screen? 
- e.g. do we put a static pointer in the middle of the screen and then the user lines that up with where they want the photo to be logged so they just have to scroll around, or can they move round the map and then "place" the pointer themselves

**Comment by lizheard1** [comment]
@munroTom to work on this

**Comment by lizheard1** [comment]
@munroTom do you need any more info or feedback from me on your above comment for this? Or was it all addressed in the zoom call?

**Comment by munroTom** [comment]
Think it was addressed in the zoom call, probs easiest to feedback once we have something coded up as it's quite interaction oriented

**Comment by lizheard1** [comment]
Cool. Just got this from a user 'Is there a way of uploaded items when I get home and have good internet but marking it in the location I collected it from rather than my home?' so looks like it is something a lot of people would want x

**Comment by lizheard1** [comment]
@munroTom what is the status of this? Please could you provide an update?

**Comment by sebastianovide** [comment]
as a work around, until when this feature will be implemented, could redirect people to https://tool.geoimgr.com/ from where they can geotag their own photos. ?
