### ISSUE TITLE
Uploads location wrong - in the middle of the ocean

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#163]
I've noticed that quite a few images logged recently are linked to a location in the middle of the ocean - https://www.google.com/maps/@0.2323,0.2323,18z - any idea why? 
Example of one where this has happened
![image](https://user-images.githubusercontent.com/62663054/89019588-6e81dd80-d315-11ea-9ef5-a3317e2e9d9e.png)

**Comment by sebastianovide** [comment]
@lizheard1 , can you still reproduce it ?

**Comment by sebastianovide** [comment]
are old photos. Cannot reproduce anymore
