### ISSUE TITLE
Logged out of app all the time - ie don't get automatically logged in

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#188]
Liz experiences this all the time, another user has also flagged this

**Comment by sebastianovide** [comment]
mmm.... iPhone ? what version of the app ? @lizheard1

**Comment by sebastianovide** [comment]
@lizheard1 do you have the same problem with the test app ?

**Comment by sebastianovide** [comment]
@lizheard1 can you still reproduce it ? what version is it ? (see in the **about** page)
