### ISSUE TITLE
App crashes on iphone when adding a brand

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#189]
A few users have said the app crashed whilst they are categorising pieces, so they fail to upload

One user has an iphone 8, and whilst typing in the brands, she is exited from the app (ie it crashes and closes)

**Comment by lizheard1** [comment]
Also just had feedback from someone saying:

Hope all is well, we started our litter logging campaign on Monday of this week and have had 56 staff sign up so far to give up at least an hour of their time and go around their local areas, we have had a few staff report issues with the app and wondered if you knew of any issues, the issues they are having is the app crashing when they try to create an account, all are using Apple devices and iOS14, I have iOS 14 on both my phones (iphone 6s and iphone XR) but the app is working for me

**Comment by sebastianovide** [comment]
ok... pepsi conspiracy ! :)

I'll try to reproduce it in Chrome (Developer Tool). It should give some error. It smells as if there is a JS error. Perhaps trying to access to a field of a null...

**Comment by sebastianovide** [comment]
I was **not** able to reproduce it in my local environment using Chrome and Safari. But I did reproduce it with my iphone

**Comment by lizheard1** [comment]
![image](https://user-images.githubusercontent.com/62663054/95353720-7f257580-08bb-11eb-8f47-807c602b0699.png)
Just had this feedback - looks like the bug is related to when a user tries to select a brand (I've had this feedback from 2 people) @sebastianovide @neilfulwiler

**Comment by sebastianovide** [comment]
confirmed. It is very easy to reproduce. Just select a brand and it will crash.

**Comment by neilfulwiler** [comment]
sorry I wasn't able to reproduce this, the steps are just: take photo, try to select brand?

**Comment by sebastianovide** [comment]
in my case (app installed on iPhone SE) just upload a picture, click on the photo to add a category, type some letters "pla" and then click on a tag, then in the brand field, type some letters "pep" and then click on any brand tag. It crashes immediately. (it works well in web, cannot test it in android as the brands are not displayed)

**Comment by neilfulwiler** [comment]
Android is updated now btw. Ok my iPhone 8 doesn’t reproduce. Will look
further

**Comment by sebastianovide** [comment]
just to confirm that I've tested it in **android**, after last deployment, and it does **not** crash.

**Comment by lizheard1** [comment]
This is still an issue for some iphone users. Email addresses are kimberleysterling@live.co.uk, alicelundy1@gmail.com  and russh82@hotmail.com

**Comment by sebastianovide** [comment]
@lizheard1 do we know what version are they using ?
