### ISSUE TITLE
brands not showing in android

### ISSUE THREAD

**Issue by sebastianovide** [PlasticPatrol/PlasticPatrolWeb#198]
the brands suggestions are not being displayed
![WhatsApp Image 2020-10-02 at 11 36 33](https://user-images.githubusercontent.com/1496395/94914836-ab985680-04a3-11eb-8b6e-0e492c7195a4.jpeg)
. I'm using the latest android verison

**Comment by lizheard1** [comment]
@sebastianovide brand drop down is in the latest beta version (do you have this on Android)?

**Comment by neilfulwiler** [comment]
Android is lagging significantly, we need to push with https://github.com/PlasticPatrol/PlasticPatrolWeb/pull/205/files. For some reason, the cache issue in android surfaced something that should have applied to both ios and android

**Comment by neilfulwiler** [comment]
android has been released
