### ISSUE TITLE
welcome page not covering the whole screen

### ISSUE THREAD

**Issue by sebastianovide** [PlasticPatrol/PlasticPatrolWeb#200]
see the screenshot
![WhatsApp Image 2020-10-02 at 11 43 49](https://user-images.githubusercontent.com/1496395/94915355-aab3f480-04a4-11eb-9a23-0220708bf724.jpeg)

**Comment by neilfulwiler** [comment]
thought this was just on desktop for some reason, will include a fix here https://github.com/PlasticPatrol/PlasticPatrolWeb/pull/205/files

**Comment by neilfulwiler** [comment]
should be fixed with !205
