### ISSUE TITLE
iphone icon still showing cordova icon

### ISSUE THREAD

**Issue by sebastianovide** [PlasticPatrol/PlasticPatrolWeb#201]
see screenshot
![IMG_B989B431D587-1](https://user-images.githubusercontent.com/1496395/94915504-ef3f9000-04a4-11eb-8f68-25fbfa7483d5.jpeg)

**Comment by neilfulwiler** [comment]
wow good spot, I have no idea which icon that is, do you know or should I start googling?

**Comment by sebastianovide** [comment]
not really sure... I guess that this link should explain: https://cordova.apache.org/docs/en/latest/config_ref/images.html

**Comment by neilfulwiler** [comment]
Yeah we have a bunch of those, I don't think much has changed here but let me look back through some PRs. I also wonder if we can just move to using a single size for all widths/heights, as it could just be a mismatch problem

**Comment by sebastianovide** [comment]
I've just searched that icon but could not find it. Just wondering if it was fixed at some point after it went live ?

**Comment by neilfulwiler** [comment]
sorry which icon do you mean?

**Comment by sebastianovide** [comment]
the cordova 
a icon (see the screenshot https://github.com/PlasticPatrol/PlasticPatrolWeb/issues/201#issue-713527996)

**Comment by neilfulwiler** [comment]
ah yeah, thats inside cordova, comes as a default
