### ISSUE TITLE
Android testing - bugs found

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#204]
I've just tested the new beta version on Android. All the new features work (barcode scanning, brand drop down list etc, images appear on map once approved) but are a three issues (one major, two not so bad)

**Map empty of 'bubbles' and images** - this should show all uploads 
- On my brothers account - only one image on the map (the one upload he's ever done), see below:
![IMG-7994](https://user-images.githubusercontent.com/62663054/94925458-274fce80-04b7-11eb-8401-c466121f9120.JPG)

- When logged out - ie no-one logged in - no images on the map, see below:
![IMG-7995](https://user-images.githubusercontent.com/62663054/94925404-11daa480-04b7-11eb-8060-8beaa323f914.JPG)

- When I logged into my account, only uploads I have done on the map, plus a random 11k uploads off the coast of Africa in the ocean
![IMG-7997](https://user-images.githubusercontent.com/62663054/94925434-1dc66680-04b7-11eb-9eaf-949bd8cf70ec.JPG)

**Apple login is an option** - can we remove this, as Android users can't login via apple
![IMG-7996](https://user-images.githubusercontent.com/62663054/94925419-18691c00-04b7-11eb-9443-7688e78d833e.JPG)

**App icon is the old logo**
![IMG-7998](https://user-images.githubusercontent.com/62663054/94925764-ab09bb00-04b7-11eb-8a70-73b87eecb111.JPG)

**Comment by neilfulwiler** [comment]
<icon density="ldpi" src="res/icon/android/icon-36-ldpi.png"/>
        <icon density="mdpi" src="res/icon/android/icon-48-mdpi.png"/>
        <icon density="hdpi" src="res/icon/android/icon-72-hdpi.png"/>
        <icon density="xhdpi" src="res/icon/android/icon-96-xhdpi.png"/>
        <icon density="xxhdpi" src="res/icon/android/icon-144-xxhdpi.png"/>
        <icon density="xxxhdpi" src="res/icon/android/icon-192-xxxhdpi.png"/>
        <splash density="land-hdpi" src="res/screen/android/landscape-hdpi.png"/>
        <splash density="land-ldpi" src="res/screen/android/landscape-ldpi.png"/>
        <splash density="land-mdpi" src="res/screen/android/landscape-mdpi.png"/>
        <splash density="land-xhdpi" src="res/screen/android/landscape-xhdpi.png"/>
        <splash density="port-hdpi" src="res/screen/android/portrait-hdpi.png"/>
        <splash density="port-ldpi" src="res/screen/android/portrait-ldpi.png"/>
        <splash density="port-mdpi" src="res/screen/android/portrait-mdpi.png"/>
        <splash density="port-xhdpi" src="res/screen/android/portrait-xhdpi.png"/>

these are the icons for android app that we need

**Comment by lizheard1** [comment]
Icon densities:
![hdpi](https://user-images.githubusercontent.com/62663054/94989436-bf5bbf80-056c-11eb-893c-7e4431d4fa13.png)
![mdpi](https://user-images.githubusercontent.com/62663054/94989438-c4207380-056c-11eb-930e-da4aaa367d4c.png)
![xhdpi](https://user-images.githubusercontent.com/62663054/94989442-c97dbe00-056c-11eb-8463-0e572eb77dee.png)
![xxhdpi](https://user-images.githubusercontent.com/62663054/94989446-ce427200-056c-11eb-9652-5a95c1bebe51.png)
![xxxhdpi](https://user-images.githubusercontent.com/62663054/94989450-d3072600-056c-11eb-9fdc-71bbd5c5341c.png)

**Comment by lizheard1** [comment]
@neilfulwiler what are the portrait and landscape splashscreens?

**Comment by neilfulwiler** [comment]
they're all 72x72 resolution but dimensions are:

720x960
320x470
320x426
480x640
960x720
470x320
426x320
642x477

?

**Comment by neilfulwiler** [comment]
@lizheard1 were you able to get these portrait/landscape icons?

**Comment by neilfulwiler** [comment]
Also missing an ldpi.png above

**Comment by lizheard1** [comment]
@neilfulwiler I've struggled to find a converter online to get the portrait / landscape icons. @joe-mcguinness please could you advise? We need portrait and landscape splashscreens (white background with the Planet Patrol logo in the middle), dimensions in the comment thread. 

Neil, I've attached the ldpi png below
![icon](https://user-images.githubusercontent.com/62663054/95714812-adf76f00-0c60-11eb-83c7-0f47a7a2bf4c.png)

**Comment by joe-mcguinness** [comment]
[android splash.zip](https://github.com/PlasticPatrol/PlasticPatrolWeb/files/5367056/android.splash.zip)
I've attached what I think you're asking for, let me know if it's alright

**Comment by neilfulwiler** [comment]
Yup those work, thank you!

**Comment by neilfulwiler** [comment]
with the updated android icons, I think we can close this (not deployed yet, but merged to main)
