### ISSUE TITLE
How many Sky staff used app and how many pieces

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#208]
Find how many Sky staff signed up to the Planet Patrol app and how many items each person logged.
They would be registered using @sky.uk or @skytv.it email addresses between 27th September and 3rd October.

@neilfulwiler @munroTom @alastairdglennie please could one of you look into this, or provide me with the steps I need to go through to extract this info so I can feedback to Sky?

**Comment by neilfulwiler** [comment]
emailed you the details, closing this for now please reopen if there's something else you need
