### ISSUE TITLE
Have to double tap brand for it to be selected on iOS, app version 2.17

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#225]

**Comment by sebastianovide** [comment]
@lizheard1 , I'm a bit confused about the version. In the appstore the live version claims to be 2.4.536 (https://apps.apple.com/gb/app/plastic-patrol/id1235072883)

**Comment by sebastianovide** [comment]
@lizheard1 I cannot reproduce it anymore from testFlight version... can you still reproduce it ?
