### ISSUE TITLE
Unit testing for cloud functions

### ISSUE THREAD

**Issue by neilfulwiler** [PlasticPatrol/PlasticPatrolWeb#234]
Need to figure out how we can unit test our cloud functions. This will probably entail setting up the emulators in CI and reconfiguring our tests/js modules so that they can be unit tested.

**Comment by neilfulwiler** [comment]
opening this because the functions are currently broken (json2csv not defined + wrong paths for missions imports). I'm fixing that up and want to make sure we can catch similar regressions

**Comment by sebastianovide** [comment]
this will be an interesting one :) 

I've seen that Travis has changed the "free" quota and that you were using github actions for a while. Should will move definitely to github actions and kill travis ?
