### ISSUE TITLE
on testflight uploaded pictures geolocation is lost

### ISSUE THREAD

**Issue by sebastianovide** [PlasticPatrol/PlasticPatrolWeb#298]

**Comment by sebastianovide** [comment]
probably caused by #295

**Comment by joykuotw** [comment]
@sebastianovide I cannot reproduce this. Uploaded pictures are with geolocation.

**Comment by sebastianovide** [comment]
> @sebastianovide I cannot reproduce this. Uploaded pictures are with geolocation.

ooo... if testflight works... perhaps was a glinch

**Comment by sebastianovide** [comment]
cannot reproduce
