### ISSUE TITLE
New teams leaderboard

### ISSUE THREAD

**Issue by joe-mcguinness** [PlasticPatrol/PlasticPatrolWeb#31]
This ticket is to create a new teams leaderboard. We're keeping this simple in the first instance for time reasons, but we may want to revisit this in future.

There will be two tabs, the main leaderboard tab and a teams-only leaderboard, it will be possible to toggle between these using the image button on the top right of the screen. I've attached a simple wireframe showing this.

The other change is to add a teams icon to teams on the main leaderboard page.

I've attached assets for the teams icon, the teams leaderboard button and the main leaderboard button, please let me know if you need these in different sizes, or have any questions.

![teams indicator](https://user-images.githubusercontent.com/31798959/80015002-06775c00-84c9-11ea-9ea2-050ca96ea7ff.png)

![main leaderboard button](https://user-images.githubusercontent.com/31798959/80014386-23f7f600-84c8-11ea-83c2-1436ba2172d1.png)
![main leaderboard button](https://user-images.githubusercontent.com/31798959/80014923-ec3d7e00-84c8-11ea-81a1-8ddf42450741.png)

<img width="1087" alt="Screenshot 2020-04-05 at 14 17 07" src="https://user-images.githubusercontent.com/31798959/80014375-1fcbd880-84c8-11ea-81ac-e94ea1d5fba2.png">

**Comment by neilfulwiler** [comment]
ok there currently isn't a concept of groups right now, which would be a prerequisite for this I'm imagining.

**Comment by joe-mcguinness** [comment]
Yeah this is just because at some point we want to add a new teams leaderboard, I've just creating the ux for it so it exists for when we're ready to do this work

**Comment by joe-mcguinness** [comment]
I'm closing this as it results from the group feature, which is now another github issue
