### ISSUE TITLE
apple is complaining about testFlight version

### ISSUE THREAD

**Issue by sebastianovide** [PlasticPatrol/PlasticPatrolWeb#313]
> Dear Developer,We identified one or more issues with a recent delivery for your app, "Planet Patrol" 2.27.112 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.After you’ve corrected the issues, you can upload a new binary to App Store Connect.Best regards,The App Store Team

**Comment by joykuotw** [comment]
This is cause by Capacitor registering for push notifications by default. This can be resolved by removing the related flag and codes.

**Comment by joykuotw** [comment]
Somehow Apple is still complaining so maybe another thirty-party plugin is using push notification underlying, probably firebase. Need to investigate that, or we can just enable push notification capability but then have to create a new provision profile.

Ref: https://developer.apple.com/forums/thread/663114

Least it is just a warning but annoying.

**Comment by sebastianovide** [comment]
as we are going to use push notifications, should we just enable them for good ?
