### ISSUE TITLE
Android target API to level 30

### ISSUE THREAD

**Issue by joykuotw** [PlasticPatrol/PlasticPatrolWeb#391]
Starting in November 2021, app updates will be required to target API level 30 or above and adjust for behavioral changes in Android 11. 

https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by lizheard1** [comment]
@joykuotw are you working on this?

**Comment by joykuotw** [comment]
@lizheard1 yes, or the new version of Android cannot be deployed.

**Comment by lizheard1** [comment]
@joykuotw thank you
