### ISSUE TITLE
Error message when try to upload

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#395]
See screenshot

Version 2.27.343
iPhone XR
user: lizheard@live.go.uk
![image](https://user-images.githubusercontent.com/62663054/141753443-825594bb-a376-4984-8935-6df6d6497048.png)

**Comment by joykuotw** [comment]
@lizheard1 the error has been fixed. It happened when you tried to upload the pick from barcode scan. Can you test it again?

**Comment by lizheard1** [comment]
Hi @joykuotw  - it's not from barcode scanning.
I selected image from camera roll, selected the location as it didn't have a geotag, typed in the type and the brand and one piece, then tried to upload and got the same error
message again![image](https://user-images.githubusercontent.com/62663054/143844144-41358ed6-5b50-4b7d-a96e-4d28b446ff9a.png)

**Comment by joykuotw** [comment]
@lizheard1 the error should be fixed now from either manual input or barcode scanning. Please update the new version to test it again on TestFlight.

**Comment by lizheard1** [comment]
@joykuotw perfect - all fixed!
