### ISSUE TITLE
New litter collection flow 

### ISSUE THREAD

**Issue by joe-mcguinness** [PlasticPatrol/PlasticPatrolWeb#41]
![Litter collection flow wireframe](https://user-images.githubusercontent.com/31798959/82732055-ccd18500-9d02-11ea-98f5-b063c0048007.png)

Below is a mockup of the link to the barcode functionality, will add a finalised button at a later date. One thing to bear in mind is that the main view here has to be a scroll view to allow space for all the text fields and buttons, I'd ideally like it to scroll the barcode button off the top of the view (behind the litter picture) when users' start typing words into the text input field, to free up some screen real estate (but this is all up for debate!)

![barcode button on view](https://user-images.githubusercontent.com/31798959/82732301-49b12e80-9d04-11ea-81cd-3464214ac4bc.png)

**Comment by munroTom** [comment]
Looks good to me!
I've got some time today so I'm just gonna start building some of the components up

@neilfulwiler do you think you'll be looking at anything today? If not I'll just pick up whatever raise a PR with what I've done at the end of the day

**Comment by munroTom** [comment]
Have made some ok progress with this so far in https://github.com/PlasticPatrol/PlasticPatrolWeb/pull/43

I've got most of the logic and some roughly styled components in for the flow once a user has selected a photo - didn't notice the edit functionality so still need to add that in

@joe-mcguinness not needed in a hurry but before release would it be possible to get exports of the designs once they're ready so that I can double check margins etc?

**Comment by joe-mcguinness** [comment]
Hi @munroTom I've uploaded all of the individual screens here: https://drive.google.com/drive/folders/1UBcVg9o8XVQLwE6Ct6jiS3lpt2-UlRUm?usp=sharing.

Let me know when and what you need exporting as individual elements, and the format you'd prefer? I know a lot of iOS guys are using pdfs so it's resizable in app

**Comment by munroTom** [comment]
@joe-mcguinness looks good to me!

I'm used to working with tools like zeplin/figma where I can click on elements to get css dimensions etc, would that be possible? 
If it isn't no worries! I'll just eyeball it as needed

Also there's a rough implementation of the flow now in #43 (still got a few things to work on) if you've got node installed on your computer and you want to have a click around (if you have any issues getting it started feel to let me know)

**Comment by joe-mcguinness** [comment]
@munroTom , I've uploaded this to figma, let me know if you need anything more: https://www.figma.com/file/SBhZ0TW416jzfLmYCRCkdy/collectionPagev3?node-id=0%3A1

**Comment by joe-mcguinness** [comment]
[mapViewIcons.zip](https://github.com/PlasticPatrol/PlasticPatrolWeb/files/4715956/mapViewIcons.zip)
