### ISSUE TITLE
Photo approval and feedback reports disappeared from menu bar for moderators

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#51]
This has happened on both my and Lizzie's accounts (both moderators), so we are unable to approve photos or view user feedback

**Comment by neilfulwiler** [comment]
yeah so I bet this was just a timeout talking to firebase to get the user info, which might indicate a bad connection or something like that but I don't really have anyway to prove that. The thing is we cache the data on the phone for the photos, but we don't cache things like "isModerator" so each time you open the app we have to pull that data from firebase. This means that that specific piece of data might fail to be fetched even though the app looks like its "fine"
