### ISSUE TITLE
Sponsored by REN Clean Skincare (logo) added to 'thank you' message after submitting a collection

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#58]

**Comment by lizheard1** [comment]
Thank you message - 'sponsored by' is on top of REN logo and button is squashed so can't read it on screen
![image](https://user-images.githubusercontent.com/62663054/83497239-17e15a00-a4b2-11ea-9347-5f63093d2ee3.png)

**Comment by munroTom** [comment]
@lizheard1 again I think this is an issue because of the browser bar as when developing I checked on an iPhone5 screen size (although annoyingly the emulators don't have the topbars which cause these issues!)

I'll try and fix the styles as it shows they are more brittle than expected though

**Comment by lizheard1** [comment]
@munroTom thanks! I'm guessing this will be ready to test again once the merge has happened?
