### ISSUE TITLE
REN logo added at base of draw like it was before

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#59]

**Comment by munroTom** [comment]
@lizheard1 in the version I've got currently it looks like it's there if this is the drawer you're talking about

If it is then when the app next gets updated it'll be there and we can close this issue

<img width="325" alt="Screenshot 2020-06-01 at 19 17 00" src="https://user-images.githubusercontent.com/29929268/83440263-8c79b180-a43c-11ea-9575-53b164fd6ec8.png">

**Comment by neilfulwiler** [comment]
yeah this should be there, it is dynamically fetched though which might fail, but we can't do much about that. please re-open if you see this consistently, but I can see it on all versions of the app so i think it was just a fluke
