### ISSUE TITLE
Tutorial update

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#62]
Update wording slighting and inclusion of image to show user what a 'clear photo' looks like.

Wording below for each swipe through frame: First part in bold, then explanatory sentence below not in bold and smaller sized font

FRAME 1:
**Step 1: Photograph litter you find**
Get outside, find a piece of litter and take a photo by clicking on the camera icon. If there are multiple pieces of litter in the photo please make sure each item is clear like in the example image below.

FRAME 2:
**Step 2: Add data about the pieces of litter in your photo**
Add the photo to the app and record details including the brand name and type of litter. Your location will be automatically registered through geotagging. When you’re sure you’ve logged all the items in your photo, submit your photo for approval.

FRAME 3:
**Step 3: View your images on the interactive map and inspire others**
Your photos and data will be approved by our team and will appear in our global litter map within 48 hours. Discard of the litter you’ve collected properly and invite others to join the app so you join forces (or compete!) with litter picking.

FRAME 4:

By litter picking and logging your findings you are helping build the largest and most powerful dataset on litter. We analyse everything you collect to drive impactful and evidence-based changes by government and brands to protect the environment. 

Your contributions are hugely valuable. Together we can measure and solve the problem.

Button: ‘get started’

**Comment by munroTom** [comment]
@lizheard1 
Can you clarify a few things:
1. is it just the initial tutorial you want updating or the tutorial page as well? 
2. if it is the initial tutorial are there any other assets you want to use on the pages? Do you want the text you've specified in bold to be in the standard app font or `Rocked Regular` (as the current slide titles are) I think all the copy and an image could be quite a lot to fill in on one page
3. what photo do you want to use to demonstrate a "clear" photo?

<img width="262" alt="Screenshot 2020-06-03 at 20 45 22" src="https://user-images.githubusercontent.com/29929268/83682005-3000c880-a5db-11ea-96c7-e23e74e650f5.png">

**Comment by lizheard1** [comment]
@munroTom it's just the tutorial actually in the app itself (the one in the drawer), not the initial welcome tutorial for users. I've attached two photos which could be used as 'clear photos' - so whichever fits best in terms of size / fit 
![ecddc4e4-6b87-468e-b3cc-a94e361ccacc](https://user-images.githubusercontent.com/62663054/83684395-db5f4c80-a5de-11ea-90bf-f127302f2aed.JPG)
![addb1981-fba3-41de-a0d9-05d21de42e7a](https://user-images.githubusercontent.com/62663054/83684397-dc907980-a5de-11ea-89fe-2421fcec739e.JPG)
