### ISSUE TITLE
Removing items from list - not obvious how to do

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#63]
removing items from the list - if you want to remove an item from the list I would have thought clicking the 'x' would do this - but it takes you through to edit the data you have inputted, and there is no option to delete - it does delete when you click cancel through which is a problem - as if you accidentally clicked the x button and didn't want to edit the item, and clicked cancel, you would lose the data you had inputted.

**Comment by neilfulwiler** [comment]
should be fixedc in https://github.com/PlasticPatrol/PlasticPatrolWeb/pull/70
