### ISSUE TITLE
Wording of 'add a photo' button

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#66]
'Add a photo' photo button - I thought this wording was changing? Is it changing to 'record your litter'?

**Comment by lizheard1** [comment]
@neilfulwiler has the wording on the button changed - when I tested this morning it says 'log your litter', could this be changed to 'record your litter' - it's a bit longer, but I think people will understand it a lot more?

**Comment by neilfulwiler** [comment]
whoops don't know how i missed that, will update

**Comment by neilfulwiler** [comment]
ok updated this in the code, but didn't push a new version

**Comment by lizheard1** [comment]
Okay great - so next time a version is pushed the wording should update? Thanks Neil
