### ISSUE TITLE
Bottom of 'welcome screens' for new users is cut off

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#71]
Welcome introduction screen - dots at bottom have disappeared so don't know you need to swipe through (or is this because it is through web and not the app?) - need to shrink to fit screen size. Some wording also cut off. If people don't know how to swipe through screens then they won't actually make it to the main app
![image](https://user-images.githubusercontent.com/62663054/83496681-575b7680-a4b1-11ea-8629-f913531efe70.png) - wording and dots cut off
![image](https://user-images.githubusercontent.com/62663054/83496736-6d693700-a4b1-11ea-95bd-72f1737cf299.png) - can't see dots

**Comment by munroTom** [comment]
Should only be an issue for mobile browsers with the top bar - but have found a fix as it makes the pwa more accessible
