### ISSUE TITLE
Synonyms for litter types

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#73]
Users (especially in different countries) will name different types of litter different things. For example 'panty liner' or 'sanitary towel', 'crisp packet' or 'chip bag'. Users may also add more info in front of the type, such as 'drinks can' or 'fizzy drinks can' and as they type 'drinks' first, the 'can' option does not appear. When they cannot find their option they will be frustrated or confused.

Solutions:
- Type we have listed appears when a user types in a synonym, for example 'sanitary towel' appears when someone types in 'panty liner'
- Type appears when in is present in any part of the words they type in (doesn't have to be at the start), for example 'can' appears when someone types in 'drinks can' or 'drinks'

Synonyms needed:

- Can - appears when user types 'drinks', 'soda', 'tin'
- Sanitary towel - appears when user types 'pad', 'period', 'menstrual', 'panty liner' 
- Lighter - appears when someone types in 'cigarette' in case they are trying to type in 'cigarette lighter'
- Footwear - appears when user types 'shoe', 'trainer', 'flip flop' or 'plimsoll' 
- Plastic fragment - appears when someone types in 'piece' or 'plastic piece'
- Metal fragment - appears as an option when someone types in 'piece' or 'metal piece'
- Plastic packaging - appears when someone types in: crisp, packet, sweet, chocolate, chip, fast food, food, supermarket, film
- Glass bottle - appears when user types 'beer', 'wine' or 'alcohol'

Over time I'm sure we'll think of more (with help of user feedback too) - is this a relatively easy thing to implement? I've seen that 'glass bottle' appears when you type in 'bottle', so that has searched the whole phrase rather than exactly how it is spelt, and 'rope' appears when you type in plastic, so I think you have done this a bit already

**Comment by munroTom** [comment]
closed by: #100
