### ISSUE TITLE
Gap between search bar for types and box for adding a brand

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#75]
![image](https://user-images.githubusercontent.com/62663054/83496917-a99c9780-a4b1-11ea-888d-5c7d88b0bd99.png)
Gap between type and brand - is this so it can be filled with 'type' tags when the user searches? 
It's a bit weird to have a gap when you're not searching - could the gap be reduced, and then expands to fit the suggested tags?

**Comment by munroTom** [comment]
closed by #100
