### ISSUE TITLE
x button over the word photo on 'please login to add a photo'

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#76]
Example here:
![image](https://user-images.githubusercontent.com/62663054/83497081-dcdf2680-a4b1-11ea-8855-8eeae0ff112a.png)

**Comment by neilfulwiler** [comment]
ok, I've removed the X and replace it with a cancel button at the bottom. This seems consistent with some of the examples here https://material-ui.com/components/dialogs/ and should avoid this sort of issue

![Screen Shot 2020-06-02 at 8 09 36 PM](https://user-images.githubusercontent.com/1045029/83559771-09745c00-a50d-11ea-83c0-3b1208da4798.png)

(ignore the photo photo thing)

**Comment by lizheard1** [comment]
Looks good!
