### ISSUE TITLE
When you click on an image, you can't view the image like you could before

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#77]
E.g. - in the image below you can see that I was trying to click on the photo with the blue circle around it, but when I clicked nothing happened
![image](https://user-images.githubusercontent.com/62663054/83497454-6b53a800-a4b2-11ea-8faa-88a167721fb2.png)

**Comment by neilfulwiler** [comment]
yup good find, I can fix that

**Comment by lizheard1** [comment]
Amazing thanks Neil
