### ISSUE TITLE
Change app name to Planet Patrol, update description and icon, add new keywords when new version is added to App and Play Store

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#78]
I tried to change the description in the app store, I was unable to as you can only change this when you push a new app version (unless I'm mistaken - please correct me if wrong!)

1. App name changed to **Planet Patrol** - we have made this decision as we have found that some users think they can only record plastic items, whereas we want them to record litter of all material types
-----
2. _Please could the **description** be changed to:_

The Planet Patrol app brings together people all over the world to make powerful and positive impacts on the environment.

This is more than just litter picking. By collecting and recording what you find it’s helping build the largest and most influential dataset on litter polluting the planet. Data collected is being used to drive positive and impactful changes by industry and governments. 

Ways we use the litter you record in the app: 

- Drives change across industry by building evidence that enables us to hold offending brands to account 
- Shapes government policy and provides tangible solutions for system change
- Creates an annual litter report that breaks down litter collected to identify wider trends and patterns, helping to accelerate system change
- Provides solutions for local authorities to better manage waste management infrastructure and implement measures to prevent littering

Using the app is simple: See it. Snap it. Map it. 

**Step one**: Take a photo of litter you collect

**Step two**: Record details including brand names and type of litter before submitting it for approval (the location is automatically geotagged). The approval process takes up to 48 hours and once complete your image will appear in the global map. The number of pieces recorded will be added to your personal profile in the leaderboard too. 

**Step three**: Discard of the litter you’ve collected properly and invite others to join the app so you join forces (or compete!) with litter picking.

Once you’ve logged your first litter haul, you can track your personal impact and that of the Planet Patrol community on our global litter map, leaderboard and your personal profile. 

You can also search for our free Plastic Patrol litter picks through the app - these are usually combined with activities like paddleboarding, yoga, parkour and canoeing.

Join thousands of people from over 85 countries across the world shaping a litter-free future together. Download the app and join the movement.

----
3. I have attached the **new image icon** here 
---
4. **Keywords** to add to originals: litter, plastic patrol, rubbish, trash, citizen science, sustainability, waste, eco
![IMG-3989](https://user-images.githubusercontent.com/62663054/83506537-37cb4a80-a4bf-11ea-86c5-254bfc77437b.PNG)

**Comment by munroTom** [comment]
New play store assets (I kept one of the original photos, but got new ones for everything else)

Feature graphic (required, 1024w x 500h)
![featureGraphic](https://user-images.githubusercontent.com/29929268/87584393-56834a80-c6d5-11ea-94c7-97e5f9051d02.png)

<img width="320" alt="Screenshot 2020-07-15 at 19 32 16" src="https://user-images.githubusercontent.com/29929268/87584456-7450af80-c6d5-11ea-86fe-7f0e922266cf.png">
<img width="320" alt="Screenshot 2020-07-15 at 19 32 31" src="https://user-images.githubusercontent.com/29929268/87584462-76b30980-c6d5-11ea-93f4-0e68eeb731cb.png">
<img width="320" alt="Screenshot 2020-07-15 at 19 36 59" src="https://user-images.githubusercontent.com/29929268/87584464-774ba000-c6d5-11ea-80b7-4ac7d39d92f7.png">
<img width="320" alt="Screenshot 2020-07-15 at 19 39 43" src="https://user-images.githubusercontent.com/29929268/87584469-77e43680-c6d5-11ea-9680-21157a68d0d0.png">
<img width="322" alt="Screenshot 2020-07-15 at 19 40 29" src="https://user-images.githubusercontent.com/29929268/87584474-79156380-c6d5-11ea-9044-74b8b5c6aa1a.png">
