### ISSUE TITLE
When you enter a custom category, it only displays the first letter when you add the item

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#88]
See example image: 
Here I had inputted 1 x Walkers crisp packet and 3 x mentos sweets wrapper - but only the first letter of crisp packet and sweet wrapper appear in the list of added items
![IMG-5570](https://user-images.githubusercontent.com/62663054/83789679-f7bac200-a68e-11ea-957b-4619882309c3.PNG)

**Comment by munroTom** [comment]
closed by #100
