### ISSUE TITLE
Replace Plastic Patrol logo with Planet Patrol logo throughout app

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#89]
As I mentioned, we are renaming the app to Planet Patrol (as it is about building evidence and recording all materials littering nature, not just plastic).

I have attached the logo in teal or white for you to use depending on the colour of the logo in the app.

Places to replace the logo:
1. First welcome tutorial screen (screenshot attached for example)
2. About section
3. App loading screen
4. Tutorial in the drawer

![PlanetPatrol-Teal](https://user-images.githubusercontent.com/62663054/83847696-959ca400-a704-11ea-926b-c74a2eab0e8f.png)
![PlanetPatrol-White](https://user-images.githubusercontent.com/62663054/83847701-99302b00-a704-11ea-951d-24e53b3fca50.png)

Replace logo in welcome screen:
![IMG_5342](https://user-images.githubusercontent.com/62663054/83848846-5e2ef700-a706-11ea-9315-24cbd090016e.PNG)

Replace logo on About section:
![IMG-5575](https://user-images.githubusercontent.com/62663054/83849725-bd413b80-a707-11ea-8dbc-db090466ed51.PNG)

Replace logo in loading screen:
![IMG-5573](https://user-images.githubusercontent.com/62663054/83849690-b4506a00-a707-11ea-8897-a373f696dfce.PNG)

Replace logos in Tutorial (in the drawer) - there is also quite a bit of white space below the logo at the moment:
![IMG-5581](https://user-images.githubusercontent.com/62663054/83849736-c5997680-a707-11ea-9726-b33ffca78d31.PNG)

**Comment by munroTom** [comment]
@lizheard1 I think to use it in the loading screen it needs to be in `svg` format - it would also make reusing it in the app much easier as developers will be able to change the color of it for different contexts so we don't need a separate file for the white and teal versions

**Comment by lizheard1** [comment]
@joe-mcguinness do you know how to convert a png to an svg? I've asked Isaac to send over svg version but not sure how quickly he'll send it over.

**Comment by joe-mcguinness** [comment]
@lizheard1 you can't really convert a png to an svg well, there are some tools online but I've never found one that works perfectly

**Comment by lizheard1** [comment]
@joe-mcguinness okay - I've chased Isaac so fingers crossed he'll get it sent over in time. Can you think of any way around not having an svg and using the PNGs instead?
